name: build_and_publish

on:
  - push
  - pull_request

env:
  branch: gh-pages

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install
        run: |
          npm install

      - name: Build
        run: |
          npm run build
      
      - name: Publish
        run: |
          if git show-ref --verify --quiet refs/heads/$branch
          then
            git checkout $branch
          else
            git checkout --orphan $branch
            git rm -rf .
          fi
          git add --all
          git commit -m 'Publish'
          git push -u origin $branch
          
      - name: TESTS
        run: |
          ls -la
          echo '============================================'
          git branch
