name: publish

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed

jobs:
  start_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dawidd6/action-download-artifact@v2
        with:
          name: build
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
      
      - name: publish
        run: |
          git config --global user.name "Keks"
          git config --global user.email "keks@htmlacademy.ru"
          git fetch --all
          if ! git checkout -t origin/gh-pages
          then
            git checkout --orphan gh-pages
            git rm -rf .
          fi
          rm -rf ${{ github.event.number }}
          unzip build.zip -d build
          mv build ${{ github.event.number }}
          git add ${{ github.event.number }}
          if git commit -m "✔️ Сборка #${{ github.event.number }}"
          then
            git push -u origin gh-pages
          else
            echo 'Nothing to commit and push'
          fi
